"""
msa_toolkit.report
==================
Shared ReportLab Platypus building blocks used by anova, capability,
and control_charts modules.  All helpers return Platypus flowable
objects or lists thereof so callers can append them into a story list
and call ``SimpleDocTemplate.build(story)``.

This module does NOT modify or duplicate grr_tool.py.  Existing PDF
output in grr_tool.py is unchanged; this module is consumed only by
the new msa_toolkit modules.

Regulatory footer text per 21 CFR 820.72 is embedded in every
``make_footer`` call.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

__all__ = [
    "NAVY", "TEAL", "ORANGE", "GREEN", "RED", "GREY",
    "palette_style",
    "make_doc",
    "make_header",
    "make_footer",
    "metrics_table",
    "section_heading",
    "embed_chart",
    "fig_to_image",
    "hr_heavy",
    "hr_light",
    "para_style",
    "REG_FOOTER",
]

# ---------------------------------------------------------------------------
# Color constants (shared across all modules)
# ---------------------------------------------------------------------------
NAVY   = "#1A3A5C"
TEAL   = "#16A085"
ORANGE = "#E67E22"
GREEN  = "#27AE60"
RED    = "#C0392B"
GREY   = "#95A5A6"

# ---------------------------------------------------------------------------
# Regulatory footer text  (21 CFR 820.72 / AIAG MSA 4th Ed.)
# ---------------------------------------------------------------------------
REG_FOOTER = (
    "Generated by msa_toolkit — AIAG MSA 4th Edition. "
    "Regulatory basis: 21 CFR Part 820.72 (FDA Quality System Regulation). "
    "This report is a controlled quality record. "
    "Retain per applicable document control procedures."
)

# ---------------------------------------------------------------------------
# Paragraph style factory
# ---------------------------------------------------------------------------

def para_style(name: str, **kw) -> ParagraphStyle:
    """
    Create a named ParagraphStyle with sensible defaults.

    Args:
        name: Unique style name (must be distinct within a document).
        **kw:  Any ParagraphStyle keyword argument overrides.

    Returns:
        A configured ``ParagraphStyle`` instance.

    Example:
        >>> s = para_style("MyTitle", fontSize=16, fontName="Helvetica-Bold")
    """
    defaults = dict(fontName="Helvetica", fontSize=9, spaceAfter=4, leading=13)
    defaults.update(kw)
    return ParagraphStyle(name, **defaults)


# ---------------------------------------------------------------------------
# Common flowables
# ---------------------------------------------------------------------------

def hr_heavy() -> HRFlowable:
    """Return a 1.5pt dark-blue horizontal rule (use after title block)."""
    return HRFlowable(width="100%", thickness=1.5, color=colors.HexColor(NAVY))


def hr_light() -> HRFlowable:
    """Return a 0.5pt light-grey horizontal rule (use between sections)."""
    return HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#D0D3D4"))


# ---------------------------------------------------------------------------
# Document factory
# ---------------------------------------------------------------------------

def make_doc(
    output_path: Path,
    title: str = "MSA Report",
    author: str = "msa_toolkit",
) -> SimpleDocTemplate:
    """
    Create a letter-size ``SimpleDocTemplate`` with standard margins.

    Args:
        output_path: Destination PDF path.
        title:       PDF document title metadata.
        author:      PDF document author metadata.

    Returns:
        A ``SimpleDocTemplate`` ready for ``.build(story)``.
    """
    return SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.65 * inch,
        bottomMargin=0.80 * inch,
        title=title,
        author=author,
        subject="MSA Report — msa_toolkit",
    )


# ---------------------------------------------------------------------------
# Header block
# ---------------------------------------------------------------------------

def make_header(
    title: str,
    metadata: Dict[str, str],
    subtitle: str = "",
) -> List:
    """
    Build a standard report header block (title + metadata table + HR).

    Args:
        title:    Main report title string.
        metadata: Ordered dict of ``{label: value}`` rows shown below the
                  title (e.g. ``{"Equipment": "CMM SN-001", "Date": "..."}``.
        subtitle: Optional single-line subtitle below the main title.

    Returns:
        List of Platypus flowables to append to a story.

    Example:
        >>> story += make_header("Capability Report", {"LSL": "9.95", "USL": "10.05"})
    """
    s_title = para_style("rpt_title", fontSize=16,
                         fontName="Helvetica-Bold",
                         textColor=colors.HexColor(NAVY),
                         alignment=1, spaceAfter=3)
    s_sub   = para_style("rpt_sub", fontSize=8.5,
                         textColor=colors.HexColor("#555555"),
                         alignment=1, spaceAfter=10)
    s_meta_k = para_style("rpt_meta_k", fontSize=8.5,
                          fontName="Helvetica-Bold",
                          textColor=colors.HexColor(NAVY))
    s_meta_v = para_style("rpt_meta_v", fontSize=8.5)

    story: List = [Paragraph(title, s_title)]
    if subtitle:
        story.append(Paragraph(subtitle, s_sub))

    rows = [[Paragraph(k, s_meta_k), Paragraph(v, s_meta_v)]
            for k, v in metadata.items()]
    if rows:
        tbl = Table(rows, colWidths=[1.9 * inch, 5.1 * inch])
        tbl.setStyle(TableStyle([
            ("FONTSIZE",       (0, 0), (-1, -1), 8.5),
            ("BOTTOMPADDING",  (0, 0), (-1, -1), 3),
            ("TOPPADDING",     (0, 0), (-1, -1), 2),
        ]))
        story += [tbl, Spacer(1, 0.08 * inch)]

    story += [hr_heavy(), Spacer(1, 0.10 * inch)]
    return story


# ---------------------------------------------------------------------------
# Footer block
# ---------------------------------------------------------------------------

def make_footer(extra_note: str = "") -> List:
    """
    Build a standard regulatory footer block.

    Args:
        extra_note: Optional additional sentence appended after the
                    standard 21 CFR 820.72 footer text.

    Returns:
        List of Platypus flowables.

    Example:
        >>> story += make_footer("Study conducted under ISO 13485 QMS.")
    """
    s_footer = para_style(
        "rpt_footer",
        fontSize=6.5,
        fontName="Helvetica-Oblique",
        textColor=colors.HexColor("#888888"),
        spaceBefore=4,
    )
    text = REG_FOOTER
    if extra_note:
        text += " " + extra_note
    return [hr_light(), Spacer(1, 4), Paragraph(text, s_footer)]


# ---------------------------------------------------------------------------
# Section heading
# ---------------------------------------------------------------------------

def section_heading(text: str) -> Paragraph:
    """
    Return a bold navy section heading paragraph.

    Args:
        text: Heading text.

    Returns:
        A ``Paragraph`` flowable.

    Example:
        >>> story.append(section_heading("Variance Components"))
    """
    s = para_style(
        f"rpt_sect_{text[:8].replace(' ', '_')}",
        fontSize=10.5,
        fontName="Helvetica-Bold",
        textColor=colors.HexColor(NAVY),
        spaceBefore=8,
        spaceAfter=4,
    )
    return Paragraph(text, s)


# ---------------------------------------------------------------------------
# Metrics table
# ---------------------------------------------------------------------------

def metrics_table(
    rows: List[List[str]],
    col_widths: Sequence[float],
    highlight_rows: Optional[List[Tuple[int, str]]] = None,
    header_color: str = NAVY,
) -> Table:
    """
    Build a styled data table with a dark header row.

    Args:
        rows:           List of row lists (first row = header).
        col_widths:     Column widths in inches.
        highlight_rows: Optional list of ``(row_index, hex_color)`` for
                        background-highlighted body rows (1-based index,
                        header is row 0).
        header_color:   Hex color for the header background.

    Returns:
        A styled ``Table`` flowable.

    Example:
        >>> tbl = metrics_table(
        ...     [["Component", "Value", "%TV"],
        ...      ["EV", "0.00872", "10.1%"]],
        ...     col_widths=[2.5, 1.2, 1.0],
        ... )
    """
    cw = [w * inch for w in col_widths]
    tbl = Table(rows, colWidths=cw, repeatRows=1)

    style_cmds = [
        ("BACKGROUND",     (0, 0),  (-1, 0),  colors.HexColor(header_color)),
        ("TEXTCOLOR",      (0, 0),  (-1, 0),  colors.white),
        ("FONTNAME",       (0, 0),  (-1, 0),  "Helvetica-Bold"),
        ("FONTSIZE",       (0, 0),  (-1, -1), 8.5),
        ("ROWBACKGROUNDS", (0, 1),  (-1, -1), [colors.HexColor("#F4F6F8"), colors.white]),
        ("GRID",           (0, 0),  (-1, -1), 0.4, colors.HexColor("#D0D3D4")),
        ("TOPPADDING",     (0, 0),  (-1, -1), 5),
        ("BOTTOMPADDING",  (0, 0),  (-1, -1), 5),
        ("LEFTPADDING",    (0, 0),  (-1, -1), 7),
        ("RIGHTPADDING",   (0, 0),  (-1, -1), 7),
        ("ALIGN",          (1, 0),  (-1, -1), "CENTER"),
        ("ALIGN",          (0, 0),  (0, -1),  "LEFT"),
    ]

    if highlight_rows:
        for row_idx, hex_color in highlight_rows:
            style_cmds += [
                ("BACKGROUND", (0, row_idx), (-1, row_idx), colors.HexColor(hex_color)),
                ("FONTNAME",   (0, row_idx), (-1, row_idx), "Helvetica-Bold"),
            ]

    tbl.setStyle(TableStyle(style_cmds))
    return tbl


# ---------------------------------------------------------------------------
# Chart embedding
# ---------------------------------------------------------------------------

def fig_to_image(fig: plt.Figure, w_in: float, h_in: float) -> Image:
    """
    Convert a matplotlib Figure to a ReportLab Image flowable.

    Args:
        fig:  Matplotlib figure (will be closed after conversion).
        w_in: Rendered width in inches.
        h_in: Rendered height in inches.

    Returns:
        A ReportLab ``Image`` flowable containing the figure as PNG.

    Example:
        >>> fig, ax = plt.subplots()
        >>> ax.plot([1, 2, 3], [4, 5, 6])
        >>> img = fig_to_image(fig, w_in=6.5, h_in=3.0)
    """
    buf = BytesIO()
    fig.savefig(buf, format="png", dpi=150, bbox_inches="tight",
                facecolor=fig.get_facecolor())
    buf.seek(0)
    img = Image(buf, width=w_in * inch, height=h_in * inch)
    plt.close(fig)
    return img


def embed_chart(fig: plt.Figure, w_in: float = 6.8, h_in: float = 3.0) -> List:
    """
    Wrap ``fig_to_image`` with standard spacing for embedding in a story.

    Args:
        fig:  Matplotlib figure.
        w_in: Chart width in inches (default 6.8 — fits letter with margins).
        h_in: Chart height in inches (default 3.0).

    Returns:
        List of [Image, Spacer] flowables.

    Example:
        >>> story += embed_chart(my_fig, w_in=6.8, h_in=2.8)
    """
    return [fig_to_image(fig, w_in, h_in), Spacer(1, 0.08 * inch)]


# ---------------------------------------------------------------------------
# Palette helper for matplotlib charts
# ---------------------------------------------------------------------------

def palette_style(ax: plt.Axes) -> None:
    """
    Apply the msa_toolkit house style to a matplotlib Axes.

    Removes top/right spines, adds light y-grid, sets axis below grid.

    Args:
        ax: Matplotlib Axes to style.

    Example:
        >>> fig, ax = plt.subplots()
        >>> palette_style(ax)
    """
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.yaxis.grid(True, linestyle=":", alpha=0.5, zorder=0)
    ax.set_axisbelow(True)
